### ISSUE TITLE
Broken syntax highlighting when .html.twig

### ISSUE THREAD

**Issue by kristijanhusak** [evidens/vim-twig#13]
I noticed one problem today, didn't happen before. When i load file which has .html.twig, syntax highlighting doesnt work properly:

![screen shot 2014-03-06 at 10 23 52 am](https://f.cloud.github.com/assets/1782860/2343586/13cc8cb6-a511-11e3-8d8e-1155f162bcc6.png)

when it's only .twig, it works fine.

![screen shot 2014-03-06 at 10 25 41 am](https://f.cloud.github.com/assets/1782860/2343607/5205aac6-a511-11e3-83e6-397c8fe43731.png)

Biggest problem in this is that i can't use my html snippets because the filetype doesn't contain html. Do you know what could be the issue here? Thanks.

**Comment by ecoleman** [comment]
Since both of the "broken highlighting" tickets are still open, I'll comment here..

A fresh install of latest vim + this plugin results in HTML not being highlighted.. It appears that `b:main_syntax` is set and is equal to `htmldjango`, not sure why that happens
