### ISSUE TITLE
Syntax highlighting lost when I open :Explore

### ISSUE THREAD

**Issue by benoliver999** [evidens/vim-twig#20]
vim-twig has been working fine, except when I open a new buffer. Then the new file is highlighted correctly, but the original one I was working on gets highlighted differently.

This is also evident in a vsplit scenario, where the text 'instantly' loses it highlighting, and seems to fall back to something else.

The only oddity I can see is that the files open as `htmldjango.twig` - but when I try to force them to `html.twig` no highlighting works at all.

**Comment by benoliver999** [comment]
I've done a little more testing, it appears to happen only when I open another `html.twig` file.

**Comment by evidens** [comment]
I don't use Vim or Twig anymore so I haven't been maintaining this for a while. You might want to look at one of the forks to see if they've solved the issue. I've added a note about the discontinued state of this repo.
